// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/dragonforce2010/chatgpt-service/client"
	"github.com/dragonforce2010/chatgpt-service/domain/chat"
	"github.com/dragonforce2010/chatgpt-service/router"
)

// Injectors from wire.go:

func InitializeRouter() *router.Router {
	clientClient := client.NewClient()
	chatService := chat.NewChatService(clientClient)
	chatHandler := chat.NewChatHandler(chatService)
	chatRouter := chat.NewChatRouter(chatHandler)
	routerRouter := router.NewRouter(chatRouter, chatHandler)
	return routerRouter
}
