package constant

const OPENAPI_PAI_KEY_COUNT = "OPENAPI_PAI_KEY_COUNT"
const OPEN_AI_API_KEY_PREFIX = "OPENAI_API_KEY_"

const CHATGPT_PARAM_TEMPERATURE = "CHATGPT_PARAM_TEMPERATURE"
const CHATGPT_PARAM_FREQUENCY_PENALTY = "CHATGPT_PARAM_FREQUENCY_PENALTY"
const CHATGPT_PARAM_PRESENCE_PENALTY = "CHATGPT_PARAM_PRESENCE_PENALTY"
const CHATGPT_PARAM_MAXTOKEN_NONE_GPT3 = "CHATGPT_PARAM_MAXTOKEN_NONE_GPT3"
const CHATGPT_PARAM_MAXTOKEN_GPT3 = "CHATGPT_PARAM_MAXTOKEN_GPT3"

const HTTPStatusCodeBadRequest = 400
const HTTPStatusCodeSuccess = 200
const HTTPStatusCodeInternalError = 500
